### ISSUE TITLE
Animation: Inputs with validation state

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design#1327]
### Goal
Design an experience that uses our micro animation tokens to notify the user that an input failed validation. This will help the user to quickly identify problem areas that require attention.

### Links
- [Figma](https://www.figma.com/design/tnfaKqovI6z0jFSuvlOEoN/PatternFly-6%3A-Motion-Design?node-id=99-6&t=c8jEmIvqHdhbkhgY-1)
- Codepen
   - [Shake](https://codepen.io/Bekah-Stephens/pen/KKOwPwr)
   - [Fade](https://codepen.io/Bekah-Stephens/pen/PoMwYwO)

```[tasklist]
### Components with validation
- [x] Form control
- [x] Form select
- [x] Text area
- [x] Text input
- [x] Menu toggle
```

```[tasklist]
### Tasks
- [x] research input and form design accessibility
- [x] create visual of motion in CodePen
- [x] use CodePen example to define motion tokens
```
